export const HANDLE_DIFFICULTY_CHANGE = 'HANDLE_DIFFICULTY_CHANGE';
export const HANDLE_MINEFIELD_CLICK = 'HANDLE_MINEFIELD_CLICK';
export const HANDLE_GAME_CLICK = 'HANDLE_GAME_CLICK';
export const HANDLE_HELP_CLICK = 'HANDLE_HELP_CLICK';